services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/project
      - ./docker_configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - postgresql-service
    networks:
      - default-network
  php74-service:
    build:
      context: .
      dockerfile: ./docker_configs/php7.4/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - default-network
  postgresql-service:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: postgresql-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - default-network
volumes:
  database_data:

networks:
  default-network: